name: MandoMC
version: '${project.version}'
main: mandomc.Main
api-version: '1.21'
author: Bilal
description: Baseline plugin structure for MandoMC

commands:
  mandomc:
    description: Main plugin command
    permission: mandomc.admin
    usage: /<command> [reload]
permissions:
  mandomc.admin:
    description: Gives access to administrative MandoMC commands
    default: op
