leaderboards:

  update-interval: 20

  kills-global:
    placeholder: "%statistic_player_kills%"
    permission-required: "mmc.leaderboards.kills"
    gradient-start: "#ff0000"
    gradient-end: "#8b0000"

    location:
      world: BlackSpireOutpost
      x: -11.730613003538814
      y: 94
      z: 21.741290597232307

  kills-all:
    placeholder: "%statistic_player_kills%"
    permission-required: ""
    gradient-start: "#ff0000"
    gradient-end: "#8b0000"

    location:
      world: Naboo
      x: -9.50608146869033
      y: 94
      z: 25.47793444293243

  money-global:
    placeholder: "%vault_eco_balance_fixed%"
    permission-required: "mmc.leaderboards.money"
    gradient-start: "#00ff66"
    gradient-end: "#008a2e"

    location:
      world: BlackSpireOutpost
      x: -9.50608146869033
      y: 94
      z: 25.47793444293243

  money-all:
    placeholder: "%vault_eco_balance_fixed%"
    permission-required: ""
    gradient-start: "#00ff66"
    gradient-end: "#008a2e"

    location:
      world: Naboo
      x: -12868
      y: 145
      z: 1301

MOTD: '            &c&lMandoMC &7x &a&lOpen now! &7[1.21]                 &3Vehicles &7- &bForce Powers &7- &2Ewok Hunt &7- &aSabers'
VersionName: 'MandoMC 1.21'
ServerListHoverText:
  - "§7§m---------------------------§r§c§lMandoMC§r§7§m---------------------------"
  - "   §cSabers §7- §6Blasters §7- §eVehicles §7- §2Ewok Hunt §7- §bForce Powers §7- §dFactions"
  - "§7§m--------------------------------------------------------------"
  - "§fWebsite: §7- §a§oComing soon..."
  - "§fDiscord: §7- §9discord.gg/3jGmpSddNt"
  - "§7§m--------------------------------------------------------------"
